
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package urouen.gil;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.xml.transform.OutputKeys;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.stream.StreamResult;
import javax.xml.transform.stream.StreamSource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;

import org.springframework.http.converter.StringHttpMessageConverter;
import org.springframework.util.LinkedMultiValueMap;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author BELKHOUS & ZEBOUCHI
 */
public class ClientApp extends javax.swing.JFrame{

    private JFileChooser chooser;
    private JTextArea jTextArea2;
    private JScrollPane jScrollPane4;
    private JTextArea jTextArea3;
    private static final String  url="http://tpweb2-anouarnabilm1gil.rhcloud.com/TPWEB2";
    private String STBNs= "<?xml version=\"1.0\" encoding=\"UTF-8\"?><p:stb xmlns:p=\"http://univ.fr/stb\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://univ.fr/stb STB.xsd\">";
    private String STBContent= STBNs;
    private String STBFooter ="</p:stb>";
    private String STBClient="";
    private String STBFunc="";
    private String STBExig="";
    private String STBEquipe="";
    private String STBComment="";
    
    ClassLoader classLoader = getClass().getClassLoader();

    Image add = null;
    Image help = null;
    Image resume = null;


    /**
     * Creates new form ClientApp
     */
    public ClientApp() throws IOException {
        add = ImageIO.read(classLoader.getResourceAsStream("add.gif"));
        help = ImageIO.read(classLoader.getResourceAsStream("refresh.gif"));
        resume = ImageIO.read(classLoader.getResourceAsStream("resume.gif"));
        initComponents();
    }

    private File fileSelected;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        homeStbApp = new javax.swing.JPanel();
        memberPanel = new javax.swing.JPanel();
        homeLabel = new javax.swing.JTextArea();
        StbDisplayPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ResultResearchTA = new javax.swing.JTextArea();
        display = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        EntityText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Contact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        CP = new javax.swing.JTextField();
        AddClient = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        IdExig = new javax.swing.JTextField();
        DescExig = new javax.swing.JTextField();
        priorityExig = new javax.swing.JTextField();
        addExig = new javax.swing.JButton();
        DescFunc = new javax.swing.JTextField();
        priorityFunc = new javax.swing.JTextField();
        addFunc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        addMember = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        stbTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        StbVersion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        StbDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        StbDesc = new javax.swing.JTextArea();
        AddGleInf = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textComment = new javax.swing.JTextArea();
        addOther = new javax.swing.JButton();
        addSTB = new javax.swing.JButton();
        TextSTBchoice = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        refrecheBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton4.setIcon(new ImageIcon(add));
        jButton2.setIcon(new ImageIcon(resume));
        jButton3.setIcon(new ImageIcon(help));
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STB Rest");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(1090, 700));

        homeStbApp.setBackground(new java.awt.Color(255, 255, 255));
        homeStbApp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 255)));
        homeStbApp.setPreferredSize(new java.awt.Dimension(250, 150));

        memberPanel.setBackground(new java.awt.Color(255, 255, 255));
        memberPanel.setName("memberPanel"); // NOI18N

        javax.swing.GroupLayout memberPanelLayout = new javax.swing.GroupLayout(memberPanel);
        memberPanel.setLayout(memberPanelLayout);
        memberPanelLayout.setHorizontalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        memberPanelLayout.setVerticalGroup(
            memberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberPanelLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(homeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout homeStbAppLayout = new javax.swing.GroupLayout(homeStbApp);
        homeStbApp.setLayout(homeStbAppLayout);
        homeStbAppLayout.setHorizontalGroup(
            homeStbAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeStbAppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(memberPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeStbAppLayout.setVerticalGroup(
            homeStbAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeStbAppLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(memberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );

        memberPanel.getAccessibleContext().setAccessibleName("memberPanel");
        memberPanel.getAccessibleContext().setAccessibleDescription("");

        StbDisplayPanel.setBackground(new java.awt.Color(255, 255, 255));
        StbDisplayPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 204, 0)));
        StbDisplayPanel.setMaximumSize(new java.awt.Dimension(600, 700));
        StbDisplayPanel.setMinimumSize(new java.awt.Dimension(600, 700));
        StbDisplayPanel.setPreferredSize(new java.awt.Dimension(600, 700));

        ResultResearchTA.setColumns(100);
        ResultResearchTA.setRows(100);
        ResultResearchTA.setText("Search results");
        ResultResearchTA.setPreferredSize(new java.awt.Dimension(804, 200));

        jScrollPane6.setViewportView(ResultResearchTA);

        javax.swing.GroupLayout StbDisplayPanelLayout = new javax.swing.GroupLayout(StbDisplayPanel);
        StbDisplayPanel.setLayout(StbDisplayPanelLayout);
        StbDisplayPanelLayout.setHorizontalGroup(
            StbDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StbDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
        );
        StbDisplayPanelLayout.setVerticalGroup(
            StbDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StbDisplayPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        display.setText("Display STB");
        display.setName("searchWithId"); // NOI18N
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 0, 0)));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Entity");

        jLabel6.setText("Contact");

        jLabel7.setText("CP");

        AddClient.setText("Add Client");
        AddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(AddClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Contact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EntityText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EntityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(AddClient)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel12.setText("Description");

        jLabel13.setText("Priority");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel14.setText("Identifier");

        jLabel15.setText("Description");

        jLabel16.setText("Priority");

        addExig.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        addExig.setText("Add exigence");
        addExig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16))
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DescExig, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(IdExig))
                    .addComponent(priorityExig, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(addExig, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdExig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescExig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priorityExig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addExig)
                .addGap(86, 86, 86))
        );

        jTabbedPane2.addTab("Exigences", jPanel6);

        addFunc.setText("Add functionality");
        addFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(priorityFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(DescFunc))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane2)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(addFunc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(DescFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(priorityFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addFunc)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Name");

        jLabel10.setText("First name");

        jLabel11.setText("Gender");

        addMember.setText("Add equipe member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addMember)
                .addGap(118, 118, 118))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(55, 55, 55)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(addMember)
                .addContainerGap(94, Short.MAX_VALUE))
        );
       
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Title");

        jLabel2.setText("Version");

        StbVersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StbVersionActionPerformed(evt);
            }
        });

        jLabel3.setText("Date");

        jLabel4.setText("Description");

        jScrollPane3.setHorizontalScrollBar(null);

        StbDesc.setColumns(20);
        StbDesc.setRows(10);
        jScrollPane3.setViewportView(StbDesc);

        AddGleInf.setText("Add general information");
        AddGleInf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    AddGleInfActionPerformed(evt);
                } catch (TransformerException ex) {
                    Logger.getLogger(ClientApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(30, 30, 30)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(StbVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AddGleInf)
                .addGap(103, 103, 103))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(StbVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StbDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(AddGleInf)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(138, 138, 138))))
        );
       
        textComment.setColumns(20);
        textComment.setRows(5);
        jScrollPane5.setViewportView(textComment);
        jLabel18.setText("Comment");
        
        addOther.setText("Add other");
        addOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOtherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addOther)
                .addGap(143, 143, 143))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel18)))
                .addGap(47, 47, 47)
                .addComponent(addOther)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addSTB.setText("Add STB");
        addSTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSTBActionPerformed(evt);
            }
        });

        jTabbedPane1.addTab("General information", jPanel2);
        jTabbedPane1.addTab("Clients", jPanel3);
        jTabbedPane1.addTab("Equipe", jPanel4);
        jTabbedPane1.addTab("Functionalities", jPanel5);
        jTabbedPane1.addTab("Other", jPanel7);
        
        jToolBar1.setRollover(true);

        jButton4.setText("Add STB file");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton2.setText("Resume STBs");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        /*refrecheBtn.setText("Refresh");
        refrecheBtn.setFocusable(false);
        refrecheBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        refrecheBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);*/
        //jToolBar1.add(refrecheBtn);

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrecheBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(addSTB)
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StbDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(display)
                        .addGap(58, 58, 58)
                        .addComponent(TextSTBchoice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeStbApp, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                        .addContainerGap(677, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeStbApp, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(StbDisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(display)
                        .addComponent(TextSTBchoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addSTB)
                    .addComponent(jButton1))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        name.setText("Not yet");  name.setEnabled(false);
        firstName.setText("Not yet");  firstName.setEnabled(false);
        gender.setText("Not yet");  gender.setEnabled(false);
        DescFunc.setText("Not yet");  DescFunc.setEnabled(false);
        priorityFunc.setText("Not yet");  priorityFunc.setEnabled(false);
        EntityText.setText("Not yet");  EntityText.setEnabled(false);
        Contact.setText("Not yet");  Contact.setEnabled(false);
        CP.setText("Not yet");  CP.setEnabled(false);
        IdExig.setText("Not yet");  IdExig.setEnabled(false);
        DescExig.setText("Not yet");  DescExig.setEnabled(false);
        priorityExig.setText("Not yet");  priorityExig.setEnabled(false);
        textComment.setText("Not yet");  textComment.setEnabled(false);
        AddClient.setEnabled(false);
        addMember.setEnabled(false);
        addOther.setEnabled(false);
        addExig.setEnabled(false);
        addFunc.setEnabled(false);
        
        new Thread(new Runnable() {
            @Override
            public void run() {
                RestTemplate restTemplate = new RestTemplate();
                String accueilText = restTemplate.getForObject(url+"/Accueil/", String.class);
                homeLabel.setText(accueilText);
            }
        }).start();
        
        pack();
    }                                       

    private void StbVersionActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) { 
        if(gender.getText().trim().equals("true") || gender.getText().trim().equals("false")){
            String nom = "<nom>"+name.getText()+"</nom>";
            String fNom = "<prenom>"+firstName.getText()+"</prenom>";
            String gen = "<gender>"+gender.getText()+"</gender>";
            STBEquipe = "<Equipe>"+nom+fNom+gen+"</Equipe>";
            STBContent+=STBEquipe;
            name.setText("");
            firstName.setText("");
            gender.setText("");
            ResultResearchTA.setText(parseXml(STBContent+STBFooter));
            
            IdExig.setText("");  IdExig.setEnabled(true);
            DescExig.setText("");  DescExig.setEnabled(true);
            priorityExig.setText("");  priorityExig.setEnabled(true);
            priorityFunc.setText("");  priorityFunc.setEnabled(true);
            DescFunc.setText("");  DescFunc.setEnabled(true);
            
            addExig.setEnabled(true);
            addFunc.setEnabled(true);
            
            EntityText.setEnabled(false);
            Contact.setEnabled(false);
            CP.setEnabled(false);
            AddClient.setEnabled(false);  
        }
        else{
            JOptionPane jop3 = new JOptionPane();
            jop3.showMessageDialog(null, "Gender must be \"true\" or \"false\"", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }                                         

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {                                        
        RestTemplate restTemplate = new RestTemplate();
        String resultText = restTemplate.getForObject(url+"/resume/"+TextSTBchoice.getText().trim(), String.class);
        ResultResearchTA.setText(parseXml(resultText));
    }
    
    private void addFuncActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String desc = "<Description>"+DescFunc.getText()+"</Description>";
        String pri = "<Priorite>"+priorityFunc.getText()+"</Priorite>";
        STBFunc = "<Fonctionnalite>"+desc+pri+STBExig+"</Fonctionnalite>";
        STBExig = "";
        STBContent+=STBFunc;
        
        DescFunc.setText("");
        priorityFunc.setText("");
        ResultResearchTA.setText(parseXml(STBContent+STBFooter));
        
        textComment.setText("");  textComment.setEnabled(true);
        addOther.setEnabled(true);
        
        name.setEnabled(false);
        firstName.setEnabled(false);
        gender.setEnabled(false);
        addMember.setEnabled(false);
    }                                       

    private void addSTBActionPerformed(java.awt.event.ActionEvent evt) {                                       
        RestTemplate template = new RestTemplate();
        MultiValueMap<String, String> parts = new LinkedMultiValueMap<String, String>();
        parts.add("xmlStream", STBContent+STBFooter);
        HttpHeaders requestHeaders = new HttpHeaders();
        requestHeaders.setContentType(MediaType.MULTIPART_FORM_DATA);
        
        String  result = template.postForObject(
                url + "/depot/stream", parts ,
                String.class);

        if(result == null){
            ResultResearchTA.setText("");
            JOptionPane jop3 = new JOptionPane();
            jop3.showMessageDialog(null, "The xml file is note valide !!\n" +
                                            "You must have one client \n" +
                                            "CP must be a number \n" +
                                            "The member equipe number must be between 2 and 7 \n" +
                                            "Priorite must be between 0 and 10 \n"+ 
                                            "You must have at least 2 Functionnality \n"+ 
                                            "You must have at least 2 exigences per Functionnality \n"                                               
                                            , "Erreur", JOptionPane.ERROR_MESSAGE);
            
			name.setText("Not yet"); name.setEnabled(false);
			firstName.setText("Not yet");firstName.setEnabled(false);
			gender.setText("Not yet");gender.setEnabled(false);
			DescFunc.setText("Not yet");DescFunc.setEnabled(false);
			priorityFunc.setText("Not yet");priorityFunc.setEnabled(false);
			textComment.setText("Not yet");textComment.setEnabled(false);
			StbVersion.setText("Not yet");StbVersion.setEnabled(false);
			StbDate.setText("Not yet");StbDate.setEnabled(false);
			StbDesc.setText("Not yet");StbDesc.setEnabled(false);
			EntityText.setText("Not yet");EntityText.setEnabled(false);
			Contact.setText("Not yet");Contact.setEnabled(false);
			CP.setText("Not yet");CP.setEnabled(false);
			IdExig.setText("Not yet");IdExig.setEnabled(false);
			DescExig.setText("Not yet");DescExig.setEnabled(false);
			priorityExig.setText("Not yet");priorityExig.setEnabled(false);
			ResultResearchTA.setText("Add Stb abort");
			stbTitle.setText(""); stbTitle.setEnabled(true);
			StbVersion.setText(""); StbVersion.setEnabled(true);
			StbDate.setText(""); StbDate.setEnabled(true);
			StbDesc.setText(""); StbDesc.setEnabled(true); AddGleInf.setEnabled(true);
			STBContent= STBNs;
			STBClient="";
			STBFunc="";
			STBExig="";
			STBEquipe="";
			STBComment="";
            JViewport jv = jScrollPane6.getViewport();
            jv.setViewPosition(new Point(0,0));
            
        }
        else{
                ResultResearchTA.setText("Your file has been saved successfully!!");
                name.setText("Not yet");  name.setEnabled(false);
                firstName.setText("Not yet");  firstName.setEnabled(false);
                gender.setText("Not yet");  gender.setEnabled(false);
                DescFunc.setText("Not yet");  DescFunc.setEnabled(false);
                priorityFunc.setText("Not yet");  priorityFunc.setEnabled(false);
                EntityText.setText("Not yet");  EntityText.setEnabled(false);
                Contact.setText("Not yet");  Contact.setEnabled(false);
                CP.setText("Not yet");  CP.setEnabled(false);
                IdExig.setText("Not yet");  IdExig.setEnabled(false);
                DescExig.setText("Not yet");  DescExig.setEnabled(false);
                priorityExig.setText("Not yet");  priorityExig.setEnabled(false);
                textComment.setText("Not yet");  textComment.setEnabled(false);
                AddClient.setEnabled(false);
                addMember.setEnabled(false);
                addOther.setEnabled(false);
                addExig.setEnabled(false);
                addFunc.setEnabled(false);

                STBContent= STBNs;
                
                stbTitle.setText(""); stbTitle.setEnabled(true);
                StbVersion.setText(""); StbVersion.setEnabled(true);
                StbDate.setText(""); StbDate.setEnabled(true);
                StbDesc.setText(""); StbDesc.setEnabled(true); AddGleInf.setEnabled(true);
            JViewport jv = jScrollPane6.getViewport();
            jv.setViewPosition(new Point(0,0));
        }
        
    }               
    
    private void addOtherActionPerformed(java.awt.event.ActionEvent evt) {                                         
        STBComment = "<Commentaire>"+textComment.getText()+"</Commentaire>";
        STBContent+=STBComment;
        textComment.setText("");
        ResultResearchTA.setText(parseXml(STBContent + STBFooter));
        
        IdExig.setEnabled(false);
        DescExig.setEnabled(false);
        priorityExig.setEnabled(false);
        priorityFunc.setEnabled(false);
        DescFunc.setEnabled(false);
        addExig.setEnabled(false);
        addFunc.setEnabled(false);
    } 

    private void AddGleInfActionPerformed(java.awt.event.ActionEvent evt) throws TransformerException {  
        if (StbDate.getText().matches("\\d{4}-\\d{2}-\\d{2}")) {
            String titre = "<Titre>"+stbTitle.getText()+"</Titre>";
            String version = "<Version>"+StbVersion.getText()+"</Version>";
            String date = "<Date>"+StbDate.getText()+"</Date>";
            String desc = "<Description>"+StbDesc.getText()+"</Description>";

            STBContent += titre+version+date+desc;
            stbTitle.setText(""); stbTitle.setEnabled(true);
            StbVersion.setText(""); StbVersion.setEnabled(true);
            StbDate.setText(""); StbDate.setEnabled(true);
            StbDesc.setText(""); StbDesc.setEnabled(true); AddGleInf.setEnabled(false);
            ResultResearchTA.setText(parseXml(STBContent + STBFooter));
            
            EntityText.setText("");  EntityText.setEnabled(true);
            Contact.setText("");  Contact.setEnabled(true);
            CP.setText("");  CP.setEnabled(true);
            AddClient.setEnabled(true);
            
            stbTitle.setText(""); stbTitle.setEnabled(false);
            StbVersion.setText(""); StbVersion.setEnabled(false);
            StbDate.setText(""); StbDate.setEnabled(false);
            StbDesc.setText(""); StbDesc.setEnabled(false); AddGleInf.setEnabled(false);
        }
        else{
            JOptionPane jop3 = new JOptionPane();
            jop3.showMessageDialog(null, "Date must respect the following format: YYYY-MM-DD", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

    } 
    
    private String parseXml(String text){
        RestTemplate restTemplate = new RestTemplate();
                restTemplate.getMessageConverters()
                .add(0, new StringHttpMessageConverter(Charset.forName("UTF-8")));
                  
                StringWriter stringWriter = new StringWriter();
                StreamResult xmlOutput = new StreamResult(stringWriter);
                TransformerFactory tf = TransformerFactory.newInstance();
                
                
                Transformer transformer;
                try {
                    transformer = tf.newTransformer();
                    transformer.setOutputProperty(OutputKeys.METHOD, "xml");
                    transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "8");
                    transformer.setOutputProperty(OutputKeys.OMIT_XML_DECLARATION, "no");
                    transformer.setOutputProperty(OutputKeys.INDENT, "yes");
                    transformer.transform(new StreamSource(new StringReader(text)), xmlOutput);

                
                } catch (TransformerConfigurationException ex) {
                    Logger.getLogger(ClientApp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (TransformerException ex) {
            Logger.getLogger(ClientApp.class.getName()).log(Level.SEVERE, null, ex);
        }
                return xmlOutput.getWriter().toString();
    }
    
    private void AddClientActionPerformed(java.awt.event.ActionEvent evt) {                                          
        String entite = "<Entite>"+EntityText.getText()+"</Entite>";
        String contacte = "<Contact>"+Contact.getText()+"</Contact>";
        String cp = "<CP>"+CP.getText()+"</CP>";
        STBClient = "<Client>"+entite+contacte+cp+"</Client>";
        STBContent+=STBClient;
       
        EntityText.setText(""); EntityText.setEnabled(false);
        Contact.setText("");	Contact.setEnabled(false);
        CP.setText("");			CP.setEnabled(false); 
        AddClient.setEnabled(false);
        ResultResearchTA.setText(parseXml(STBContent+STBFooter));
        
        name.setText("");  name.setEnabled(true);
        firstName.setText("");  firstName.setEnabled(true);
        gender.setText("");  gender.setEnabled(true);
        addMember.setEnabled(true);
    }
    
    private void addExigActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String idEx = "<Identifiant>"+IdExig.getText()+"</Identifiant>";
        String descE = "<Description>"+DescExig.getText()+"</Description>";
        String prio = "<Priorite>"+priorityExig.getText()+"</Priorite>";
        STBExig += "<Exigence>"+ idEx+descE+prio +"</Exigence>";
        IdExig.setText("");
        DescExig.setText("");
        priorityExig.setText("");
                
    } 
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        chooser = new JFileChooser();
              chooser.addActionListener(new ActionListener() {
                  @Override
                  public void actionPerformed(ActionEvent e) {
                      if (chooser.getSelectedFile() != null) {
                          if (!(chooser.getSelectedFile().getName().endsWith(".xml"))) {
                              JOptionPane.showMessageDialog(new JFrame(),"Le format de fichier est incorrect, veuillez choisir un format .xml", "Erreur Format Fichier",
                                      JOptionPane.ERROR_MESSAGE);
                              
                          } else {
                                    fileSelected = chooser.getSelectedFile();
                                    RestTemplate template = new RestTemplate();

                                    Resource resource = new FileSystemResource(fileSelected.getPath());
                                    MultiValueMap<String, Object> parts = new LinkedMultiValueMap<String, Object>();
                                    parts.add("file", resource);

                                    ResponseEntity<String> result = template.exchange(
                                            url + "/depot", HttpMethod.POST, new HttpEntity<MultiValueMap<String, Object>>(parts),
                                            String.class);

                                    if(result.getBody() == null){
                                        ResultResearchTA.setText("");
                                        JViewport jv = jScrollPane6.getViewport();
                                        jv.setViewPosition(new Point(0,0));
                                        JOptionPane jop3 = new JOptionPane();
                                        jop3.showMessageDialog(null, "The xml file is note valide !!\n" +
                                            "You must have one client \n" +
                                            "CP must be a number \n" +
                                            "The member equipe number must be between 2 and 7 \n" +
                                            "Priorite must be between 0 and 10 \n"+ 
                                            "You must have at least 2 Functionnality \n"+ 
                                            "You must have at least 2 exigences per Functionnality \n"                                               
                                            , "Erreur", JOptionPane.ERROR_MESSAGE);
                                        
                                            name.setText("Not yet"); name.setEnabled(false);
                                            firstName.setText("Not yet");firstName.setEnabled(false);
                                            gender.setText("Not yet");gender.setEnabled(false);
                                            DescFunc.setText("Not yet");DescFunc.setEnabled(false);
                                            priorityFunc.setText("Not yet");priorityFunc.setEnabled(false);
                                            textComment.setText("Not yet");textComment.setEnabled(false);
                                            StbVersion.setText("Not yet");StbVersion.setEnabled(false);
                                            StbDate.setText("Not yet");StbDate.setEnabled(false);
                                            StbDesc.setText("Not yet");StbDesc.setEnabled(false);
                                            EntityText.setText("Not yet");EntityText.setEnabled(false);
                                            Contact.setText("Not yet");Contact.setEnabled(false);
                                            CP.setText("Not yet");CP.setEnabled(false);
                                            IdExig.setText("Not yet");IdExig.setEnabled(false);
                                            DescExig.setText("Not yet");DescExig.setEnabled(false);
                                            priorityExig.setText("Not yet");priorityExig.setEnabled(false);
                                            ResultResearchTA.setText("Add Stb abort");
                                            stbTitle.setText(""); stbTitle.setEnabled(true);
                                            StbVersion.setText(""); StbVersion.setEnabled(true);
                                            StbDate.setText(""); StbDate.setEnabled(true);
                                            StbDesc.setText(""); StbDesc.setEnabled(true); AddGleInf.setEnabled(true);
                                            STBContent= STBNs;
											STBClient="";
											STBFunc="";
											STBExig="";
											STBEquipe="";
											STBComment="";
                                    }
                                    else{
                                        ResultResearchTA.setText("Your file has been saved successfully!!");
                                        JViewport jv = jScrollPane6.getViewport();
                                        jv.setViewPosition(new Point(0,0));
                                    }
                          }               
                      }
                  }
              });
              chooser.showOpenDialog(null);
    }      
    
    private void refrecheBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        new Thread(new Runnable() {
            @Override
            public void run() {
                RestTemplate restTemplate = new RestTemplate();
                String accueilText = restTemplate.getForObject(url+"/Accueil/", String.class);
                homeLabel.setText(accueilText);
            }
        }).start();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        name.setText("Not yet"); name.setEnabled(false);
        firstName.setText("Not yet");firstName.setEnabled(false);
        gender.setText("Not yet");gender.setEnabled(false);
        DescFunc.setText("Not yet");DescFunc.setEnabled(false);
        priorityFunc.setText("Not yet");priorityFunc.setEnabled(false);
        textComment.setText("Not yet");textComment.setEnabled(false);
        StbVersion.setText("Not yet");StbVersion.setEnabled(false);
        StbDate.setText("Not yet");StbDate.setEnabled(false);
        StbDesc.setText("Not yet");StbDesc.setEnabled(false);
        EntityText.setText("Not yet");EntityText.setEnabled(false);
        Contact.setText("Not yet");Contact.setEnabled(false);
        CP.setText("Not yet");CP.setEnabled(false);
        IdExig.setText("Not yet");IdExig.setEnabled(false);
        DescExig.setText("Not yet");DescExig.setEnabled(false);
        priorityExig.setText("Not yet");priorityExig.setEnabled(false);
        ResultResearchTA.setText("Add Stb abort");
        stbTitle.setText(""); stbTitle.setEnabled(true);
        StbVersion.setText(""); StbVersion.setEnabled(true);
        StbDate.setText(""); StbDate.setEnabled(true);
        StbDesc.setText(""); StbDesc.setEnabled(true); AddGleInf.setEnabled(true);
        STBContent= STBNs;
		STBClient="";
		STBFunc="";
		STBExig="";
		STBEquipe="";
		STBComment="";
        JViewport jv = jScrollPane6.getViewport();
        jv.setViewPosition(new Point(0,0));
    } 
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        new Thread(new Runnable() {
            @Override
            public void run() {
                RestTemplate restTemplate = new RestTemplate();                  
                List<String> resumeStbs = restTemplate.getForObject(url+"/resume/", List.class);
                String resultResume ="";
                if(resumeStbs!=null){
                    for(String line:resumeStbs){
                        resultResume+=line+"\n----------------------------------------------------------------\n";
                    }
                    ResultResearchTA.setText(resultResume);
                    JViewport jv = jScrollPane6.getViewport();
                    jv.setViewPosition(new Point(0,0));
                }
                else{
                    ResultResearchTA.setText("There is no STB in the DB!!");
                }                        
            }
        }).start();
    } 
    
     public static void main(String[] args){       
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ClientApp().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ClientApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
         
     }
     
     // Variables declaration - do not modify                     
    private javax.swing.JButton AddClient;
    private javax.swing.JButton AddGleInf;
    private javax.swing.JTextField CP;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField DescExig;
    private javax.swing.JTextField DescFunc;
    private javax.swing.JTextField EntityText;
    private javax.swing.JTextField IdExig;
    private javax.swing.JTextArea ResultResearchTA;
    private javax.swing.JTextField StbDate;
    private javax.swing.JTextArea StbDesc;
    private javax.swing.JPanel StbDisplayPanel;
    private javax.swing.JTextField StbVersion;
    private javax.swing.JTextField TextSTBchoice;
    private javax.swing.JButton addExig;
    private javax.swing.JButton addFunc;
    private javax.swing.JButton addMember;
    private javax.swing.JButton addSTB;
    private javax.swing.JButton display;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextField gender;
    private javax.swing.JTextArea homeLabel;
    private javax.swing.JPanel homeStbApp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel memberPanel;
    private javax.swing.JTextField name;
    private javax.swing.JTextField priorityExig;
    private javax.swing.JTextField priorityFunc;
    private javax.swing.JTextField stbTitle;
    private javax.swing.JButton refrecheBtn;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextArea textComment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton addOther;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration 
     
}
