@startuml

title Diagramme de cas d'utilisation\nde la modification d'un diagramme de classe

Actor :user:

rectangle {
       (Relation) as (lien)
       (Créer/Supprimer/Cacher/Modifier) as crrmed
 
	:user: - (crrmed)
		
	(crrmed) <|-- (lien)    
	(crrmed) <|-- (Entité)
        (Entité) <|-- (Note)   
        (Entité) <|-- (Classe)      
	(Entité) <|-- (Interface) 

	note bottom of (Entité)
            Possibilité de modifier la visibilité 
            et la position de nos entités
	end note
	
	


@enduml